### ISSUE TITLE
Configuration is wiped every time I restart server

### ISSUE THREAD

**Issue by funwhilelost** [solidusio-contrib/solidus_tax_cloud#4] opened 2017-02-21 05:34 UTC
Every time the server is restarted the values in my Settings > Store > TaxCloud Settings are wiped out.

**Comment by brchristian** [comment] 2017-02-22 01:45
Hmm, I’m not able to reproduce in my app which is on the latest `master`. Are you able to reproduce this in a new Solidus app?

**Comment by rlasch** [comment] 2017-04-24 18:19
I am seeing this as well, but it's not clear when/why this is happening.  I think I'm going to hunt this down.

**Comment by hf2186** [comment] 2017-06-08 20:38
Yeah this is happening for me too. Created a new solidus app v2.2

**Comment by hf2186** [comment] 2017-07-10 02:24
I have a fix for this issue.

**Comment by brchristian** [comment] 2017-07-10 14:34
@hf2186 PR is welcome! 👍

**Comment by hf2186** [comment] 2017-07-10 16:22
@brchristian I am new to TravisCI. The PR is failing. Any insight on that would be appreciated.

**Comment by brchristian** [comment] 2017-12-15 17:56
@funwhilelost The fix from @hf2186 was right on the money. This is now merged to `v2.2`, `v2.3`, and `master`.

**Comment by hf2186** [comment] 2017-12-15 17:57
Can you update the readme for some reason the formatting become messed up

**Closed as completed by brchristian** 2017-12-15 17:56 UTC

**Comment by brchristian** [comment] 2017-12-15 18:41
@hf2186 It looks okay to me - which part is messed up?

**Comment by hf2186** [comment] 2017-12-15 18:42
Looks right now. It was the 

TaxCloud.configure do |config|
  config.api_login_id = 'YOUR_TAX_CLOUD_API_ID'
  config.api_key = 'YOUR_TAX_CLOUD_API_KEY'
end

**Comment by brchristian** [comment] 2017-12-15 18:44
What about it is messed up? Sorry for being dense...

**Comment by hf2186** [comment] 2017-12-15 18:51
It has been fixed with a later commit you just made. Thanks!
